# Generated by Django 3.1.3 on 2022-02-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220205_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modify_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modify_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
